Update ImportMemories App
Azure-Samples/semantic-kernel-rag-chat pull request #13
Opened 2023-09-18 13:36 UTC by raykao

Updating the src/importmemories service to use SK v0.24.230912.2-preview

Several kernel builder/config methods have been deprecated/changed - updated to use latest/current as of at least v0.24

Also fixed/added missing textembeddingservice configuration for Azure Cognitive search section of memory import.  Azure Cognitive Search does not include an embeddings model, users/apps must create embedding first and as such the kernel should/must provide an embedding model/service to do so before saving to Azure Cognitive Search (https://learn.microsoft.com/en-us/azure/search/vector-search-how-to-generate-embeddings)

2023-09-28 00:23 UTC, gitri-ms requested changes
Made some suggestions -- most of it is just bringing the README in line with your changes. Lmk if you need any help or want me to push updates directly. Thank you for doing this!

2023-09-28 00:23 UTC, gitri-ms commented on README.md
> +    dotnet add package Microsoft.SemanticKernel --prerelease -v dotnet-0.24.230918.1-preview
```suggestion
    dotnet add package Microsoft.SemanticKernel -v 0.24.230918.1-preview
```

2023-09-28 00:23 UTC, gitri-ms commented on README.md
> +    dotnet add package Microsoft.SemanticKernel.Connectors.Memory.Qdrant --prerelease -v dotnet-0.24.230918.1-preview
```suggestion
    dotnet add package Microsoft.SemanticKernel.Connectors.Memory.Qdrant -v 0.24.230918.1-preview
```

2023-09-28 00:23 UTC, gitri-ms commented on README.md
> +
nit: remove extra blank line

2023-09-28 00:23 UTC, gitri-ms commented on README.md
> +    dotnet add package Microsoft.SemanticKernel.Connectors.Memory.AzureCognitiveSearch --prerelease -v dotnet-0.24.230918.1-preview
```suggestion
    dotnet add package Microsoft.SemanticKernel.Connectors.Memory.AzureCognitiveSearch -v 0.24.230918.1-preview
```

2023-09-28 00:23 UTC, gitri-ms commented on src/chapter2/Program.cs
> +
nit: remove extra blank line

2023-09-28 00:23 UTC, gitri-ms commented on src/chapter1/Chapter1Function.cs
> +            _chatHistory!.AddMessage(AuthorRole.User, await req.ReadAsStringAsync() ?? string.Empty);
Update the code snippets in README with this change

2023-09-28 00:23 UTC, gitri-ms commented on README.md
>  1. Open your Program code file (e.g., `Program.cs`) and add the Qdrant memory store using statement to the top.
Update this code snipped to parse host/port from QDRANT_ENDPOINT (you did it below at line ~432, just missed it here). Also provide instruction for setting the QDRANT_ENDPOINT variable.

2023-10-02 14:24 UTC, raykao reviewed
LGTM :)

2023-10-02 14:26 UTC, raykao reviewed
Thanks for making the changes.  LGTM

2024-01-21 00:24 UTC, closed without merging